### ISSUE TITLE
AtmosControl UI error

### ISSUE THREAD

**Issue by Naxodile** [AstroHaven-13/Haven-Urist#164]
#### Description of issue
When attempting to open the atmos control program on any computer, you receive a "missing an export" error.
![image](https://user-images.githubusercontent.com/16085952/150558753-7a7455a4-0237-4200-af3b-d904a9975692.png)

#### Difference between expected and actual behavior

Atmos control is unusable

#### Steps to reproduce 

Attempt to load the Atmos Control program

#### Client version, Server revision & Game ID
Client Version: 514
Server Revision: 0f13778
Game ID: (whoops, I forgot to grab this last night)
Current map: AFCUV Pluto

**Comment by martinlyra** [comment]
The tgUI for it exists. But it does not seem to be integrated and the export name is wrong.
https://github.com/Haven-13/Haven-Urist/blob/latest/tgui/packages/tgui/interfaces/programs/AtmosControlProgram.js

As seen here: https://github.com/Haven-13/Haven-Urist/blob/0f13778dfab23a759a2e8141664a59698a1c97ef/tgui/packages/tgui/interfaces/programs/AtmosControlProgram.js#L9

(In tgUI, the UI that should be shown must have the same exported class name as the source file's name.)

**Comment by martinlyra** [comment]
Update: This is worse than I thought. NtosAtmos is tgstation's gas analyzer for modular computers, for some reason...
