### ISSUE TITLE
UIs lack permission checks

### ISSUE THREAD

**Issue by Naxodile** [AstroHaven-13/Haven-Urist#165]
#### Description of issue

The new UIs do not have a permissions/ghost check and can be controlled.

#### Difference between expected and actual behavior

Ghostly engineers should not open the release valve.

#### Steps to reproduce 

Click on any SMES/PSU/Canister/APC/Atmos equipment/etc. as a ghost without permissions, have full access

#### Client version, Server revision & Game ID
Client Version: 514
Server Revision: 0f13778
Game ID: (whoops, I forgot to grab this last night)
Current map: AFCUV Pluto

**Comment by martinlyra** [comment]
The premission checks always allow admin-ghosts to interact with the UI. So I should try to reproduce the issue by being an admin-ghost then deadmin to see if it stays the same.
