### ISSUE TITLE
Boarding pirates lack sprites

### ISSUE THREAD

**Issue by Naxodile** [AstroHaven-13/Haven-Urist#166]
#### Description of issue
Yaargh
![image](https://user-images.githubusercontent.com/16085952/150560305-0eb0ea46-3eca-4db1-9616-3c52fd5e8145.png)

#### Difference between expected and actual behavior

You get the idea.

#### Steps to reproduce 

Engage in combat, have boarders spawn, observe boarders

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: 0f13778
Game ID: (whoops, I forgot to grab this last night)
Current map: AFCUV Pluto

**Comment by martinlyra** [comment]
Issue associated with the #159 PR
