### ISSUE TITLE
Main elevator has incorrect turf defaults

### ISSUE THREAD

**Issue by Naxodile** [AstroHaven-13/Haven-Urist#167]
#### Description of issue

Upon arriving at the lowest Z in the elevator, have your floor become void.
![image](https://user-images.githubusercontent.com/16085952/150560800-1bf27699-1a38-4e1a-8225-4f84e5d64d30.png)

#### Difference between expected and actual behavior

Not having a portal to hell open up when using an elevator

#### Steps to reproduce 

Bring elevator to any floor above 3, go down to 3.

#### Client version, Server revision & Game ID
Client Version: 514
Server Revision: 0f13778
Game ID: (whoops, I forgot to grab this last night)
Current map: AFCUV Pluto

**Comment by martinlyra** [comment]
GODDAMN DEFAULT TURFS
